//! Shared state for wasmtime Component Model host functions.
//!
//! [`HostState`] is used as the `T` in `wasmtime::Store<T>` and is directly
//! accessible to all host trait implementations generated by `bindgen!`.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;

use tokio::sync::{Semaphore, mpsc, watch};
use tokio_util::sync::CancellationToken;

use crate::capsule::CapsuleId;
use astrid_core::local_transport::{LocalListener, LocalStream};
use astrid_core::uplink::{InboundMessage, MAX_UPLINKS_PER_CAPSULE, UplinkDescriptor};
use astrid_storage::ScopedKvStore;
use astrid_storage::secret::SecretStore;

/// An active network stream owned by a capsule.
///
/// Holds either an inbound host-local connection (accepted from the
/// capsule's pre-provisioned listener) or an outbound TCP connection
/// (opened via `net.connect-tcp`). The read/write/close host fns
/// dispatch on the variant; both variants implement
/// [`tokio::io::AsyncRead`] / [`tokio::io::AsyncWrite`], so the inner
/// framing logic is shared.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum NetStream {
    /// Inbound Unix-domain socket accepted from the kernel's listener.
    Unix(Arc<tokio::sync::Mutex<LocalStream>>),
    /// Outbound TCP connection opened via `net.connect-tcp`.
    Tcp(TcpStreamSlot),
}

/// Per-stream state for an outbound TCP connection.
///
/// Holds the raw [`tokio::net::TcpStream`] (behind an `Arc<Mutex<…>>` so
/// host fns that all take `&mut HostState` can each lock it cooperatively)
/// plus the std-style configurable socket options that the WIT surface
/// exposes — read/write timeouts. `TCP_NODELAY` and `TTL` are not cached
/// here; they live on the underlying socket and are read back via
/// `TcpStream::nodelay()` / `ttl()` on demand.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct TcpStreamSlot {
    /// The connected TCP socket. Shared via `Arc<Mutex<…>>` so the
    /// existing `net-read` / `net-write` dispatchers can clone the
    /// outer `NetStream` and then lock the inner stream.
    pub stream: Arc<tokio::sync::Mutex<tokio::net::TcpStream>>,
    /// Read timeout applied to each `net-read-bytes` / `net-peek` call.
    /// `None` → use the host default (~50 ms poll for `Pending` parity
    /// with `net-read`).
    pub read_timeout: Option<std::time::Duration>,
    /// Write timeout applied to each `net-write-bytes` call.
    /// `None` → no extra timeout beyond the host cancellation token.
    pub write_timeout: Option<std::time::Duration>,
}

/// One bound loopback TCP listener plus the number of live guest slots
/// holding it. The last slot drop evicts the registry entry so the OS
/// socket actually closes.
pub struct SharedTcpListener {
    pub listener: Arc<tokio::net::TcpListener>,
    pub holders: std::sync::atomic::AtomicUsize,
}

/// The lifecycle phase a capsule is currently executing in.
///
/// Set on [`HostState`] during `#[install]` or `#[upgrade]` dispatch.
/// The `astrid_elicit` host function checks this field and rejects calls
/// outside of a lifecycle phase.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LifecyclePhase {
    /// First-time installation.
    Install,
    /// Upgrading from a previous version.
    Upgrade,
}

/// Metadata for an interceptor binding declared in `Capsule.toml`.
///
/// Under the new per-domain WIT, interceptors are NOT capsule-side
/// `Resource<Subscription>` handles — the kernel matches incoming IPC
/// messages against interceptor patterns and dispatches them directly
/// to `astrid-hook-trigger`. This struct exists purely to:
///
/// 1. Let the guest enumerate what it's subscribed to via
///    `astrid:ipc/host.get-interceptor-bindings` (debugging /
///    tooling), and
/// 2. Anchor the registry-side routing table used by the run-loop
///    dispatcher.
///
/// `handle_id` is informational only — the guest cannot turn it
/// back into a `Resource<Subscription>` and the kernel does not key
/// any storage on it.
#[derive(Debug, Clone, serde::Serialize)]
#[non_exhaustive]
pub struct InterceptorHandle {
    /// Enumeration index; informational only under the new ABI.
    pub handle_id: u64,
    /// The interceptor action name from the manifest.
    pub action: String,
    /// The event topic this interceptor subscribes to.
    pub topic: String,
}

use crate::engine::wasm::host::process::ProcessTracker;
use crate::security::CapsuleSecurityGate;

/// Cancellation tokens admitted within one authority-scoped runtime.
///
/// Principal runtimes normally contain one durable identity. Explicit
/// SystemResident services may multiplex authenticated callers, so this map
/// gives cancellation the same granularity as attribution overlays: each is a
/// [`child_token`](CancellationToken::child_token) of the instance token (so a
/// full-instance cancel still cascades to every principal), minted lazily by
/// the per-invocation overlay installer and cancelled + removed when that
/// principal's view of the runtime is released. One map per engine, cloned
/// into every pooled `HostState`, so a per-principal cancel reaches waits on
/// any pooled instance.
pub type PrincipalCancelTokens =
    Arc<std::sync::Mutex<HashMap<astrid_core::principal::PrincipalId, CancellationToken>>>;

/// Location authority for a principal-scoped filesystem mount.
#[derive(Clone, Debug)]
#[non_exhaustive]
pub enum PrincipalMountLocation {
    /// Authoritative path-free AstridFilesystem namespace.
    AstridFilesystem,
    /// Ephemeral/native host directory (currently only the private `/tmp`
    /// scratch projection; lifecycle `home://` never uses this location).
    Native(PathBuf),
}

/// A principal-scoped filesystem mount: location, VFS, and capability handle.
///
/// The capability handle is confined to the specific [`Vfs`](astrid_vfs::Vfs)
/// instance. AstridFilesystem mounts are logical and therefore carry no host
/// path; native mounts carry their canonical path only for `/tmp`. The fields
/// must always be installed and
/// cleared as a unit, so callers cannot accidentally pair an
/// invocation-scoped VFS with a load-time handle (which would break capability
/// confinement).
///
/// `Clone` lets the Store pool hand the same principal mount to each of a
/// capsule's pooled instances; the VFS is shared and the capability handle is
/// cheap to copy.
#[derive(Clone)]
#[non_exhaustive]
pub struct PrincipalMount {
    /// Authority location. AstridFilesystem mounts carry no host path.
    pub location: PrincipalMountLocation,
    /// VFS bound to the mount's capability handle. Native scratch mounts use
    /// [`HostVfs`](astrid_vfs::HostVfs); durable home mounts use the
    /// path-free AstridFilesystem adapter.
    pub vfs: Arc<dyn astrid_vfs::Vfs>,
    /// Capability handle that confines access to `root`.
    pub handle: astrid_capabilities::DirHandle,
}

/// Resolver for an invocation's authoritative workspace branch.
///
/// Shared/SystemResident runtimes use this to bind the authenticated caller
/// to one durable branch without exposing a caller-selected owner or path.
#[async_trait::async_trait]
pub trait WorkspaceMountResolver: Send + Sync {
    /// Resolve (or create) the caller's branch mount, or fail closed.
    async fn resolve(
        &self,
        principal: &astrid_core::principal::PrincipalId,
    ) -> Result<PrincipalMount, String>;
}

impl std::fmt::Debug for PrincipalMount {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PrincipalMount")
            .field("location", &self.location)
            .field("handle", &self.handle)
            .finish_non_exhaustive()
    }
}

/// Verified identity bound to an accepted host-local connection.
///
/// Pairs the handshake-verified [`PrincipalId`](astrid_core::principal::PrincipalId)
/// with the `key_id` of the [`DeviceKey`](astrid_core::profile::DeviceKey)
/// whose pubkey verified the challenge signature. Held as one unit in the
/// per-connection registry so the principal and the device that authenticated
/// it can never desync — the uplink forwards BOTH onto outbound traffic, so
/// the cap-gate can apply the device's scope as an attenuation floor.
///
/// `device_key_id` is `Option` because a Path-1 (peer-cred-trusted, no
/// keypair challenge) binding can carry a principal with no specific device.
/// In practice the socket challenge path always yields `Some`, but the type
/// keeps the field honest for any future principal binding that is not
/// device-scoped.
#[derive(Clone, Debug)]
#[non_exhaustive]
pub struct ConnectionIdentity {
    /// The handshake-verified principal this connection authenticated as.
    pub principal: astrid_core::principal::PrincipalId,
    /// The `key_id` of the device key that verified the challenge, if the
    /// principal authenticated via the keypair challenge.
    pub device_key_id: Option<String>,
    /// Opaque owner minted for this authenticated connection. Interactive
    /// responses must carry this exact host-stamped value.
    pub request_owner: astrid_events::ipc::RequestOwnerId,
}

/// Caller-supplied inputs for [`HostState::for_hook`].
///
/// Carries only the pieces a transient WASM hook invocation genuinely varies —
/// identity, VFS, KV, secret store, HTTP limits, runtime handle, and the process
/// registries. Every other [`HostState`] field is the fail-closed hook default
/// filled in by [`HostState::for_hook`]. Grouping these in one struct keeps the
/// hook crate off the giant field-by-field literal, so [`HostState`] can gain
/// fields (`#[non_exhaustive]`) without breaking `astrid-hooks`.
pub struct HookHostStateParams {
    /// Per-Store memory meter (throwaway ledger; the cap is still enforced).
    pub store_meter: crate::memory_ledger::StoreMemoryMeter,
    /// Per-module hook identity (`hook:{module_stem}`).
    pub capsule_id: CapsuleId,
    /// Workspace root; file operations are confined here.
    pub workspace_root: PathBuf,
    /// VFS confining the hook to `workspace_root`.
    pub vfs: Arc<dyn astrid_vfs::Vfs>,
    /// Root capability handle for the VFS.
    pub vfs_root_handle: astrid_capabilities::DirHandle,
    /// The hook's own KV store (a single-principal one-shot, not a shared
    /// runtime, so this legitimately IS the hook's store — no overlays).
    pub kv: ScopedKvStore,
    /// Backing KV handle, mirroring [`kv`](Self::kv) for API completeness.
    pub kv_backend: Arc<dyn astrid_storage::KvStore>,
    /// Per-module secret store (scoped to the hook identity).
    pub secret_store: Arc<dyn SecretStore>,
    /// Operator `astrid:http` host policy applied to the hook's HTTP calls.
    pub http_limits: super::limits::HttpLimits,
    /// Event bus for IPC publish/subscribe.
    pub event_bus: astrid_events::EventBus,
    /// Tokio runtime handle for bridging async in sync host fns.
    pub runtime_handle: tokio::runtime::Handle,
    /// Child-process tracker (throwaway; reaped on drop).
    pub process_tracker: Arc<ProcessTracker>,
    /// Persistent-process registry (throwaway; hooks never spawn persistent
    /// children).
    pub persistent_processes: Arc<crate::engine::wasm::host::process::PersistentProcessRegistry>,
}

/// Shared state accessible to all host functions via `Store<HostState>`.
#[non_exhaustive]
pub struct HostState {
    /// WASI context for Component Model WASI imports (clocks, random, etc.).
    pub wasi_ctx: wasmtime_wasi::WasiCtx,
    /// Resource table for WASI resource types (streams, descriptors, etc.).
    pub resource_table: wasmtime::component::ResourceTable,
    /// Per-Store memory limiter: enforces the per-invocation linear-memory
    /// ceiling **and** records the invoking principal's peak into the shared
    /// memory ledger. Wired via `Store::limiter`; re-targeted per invocation
    /// (cap + attributee principal) since a pooled Store crosses principals.
    /// Replaces a plain `wasmtime::StoreLimits`.
    pub store_meter: crate::memory_ledger::StoreMemoryMeter,
    /// The principal this capsule is running on behalf of.
    pub principal: astrid_core::principal::PrincipalId,
    /// Explicit kernel-service scope. When false, every long-lived IPC route
    /// is restricted to `principal`; default-principal is still a principal.
    pub system_runtime: bool,
    /// The plugin this state belongs to.
    pub capsule_id: CapsuleId,
    /// Per-capsule native operational log under
    /// `log/principals/<immutable-uid>/<capsule>/<date>.log`.
    /// Capsule `astrid_log` output writes here instead of the system tracing
    /// subscriber. `None` if the log file couldn't be opened.
    pub capsule_log: Option<Arc<std::sync::Mutex<std::fs::File>>>,
    /// Context of the current caller (set per-invocation by the dispatcher).
    pub caller_context: Option<astrid_events::ipc::IpcMessage>,
    /// `true` while a kernel-dispatched interceptor is executing.
    ///
    /// Set by `WasmEngine::invoke_interceptor` around the typed-func
    /// call and read by `install_recv_invocation_context` to detect
    /// that `caller_context` is owned by the *outer* interceptor
    /// invocation, not by recv. Without this flag a nested
    /// `ipc::recv` that drained a message from a different publisher
    /// would rewrite the interceptor's caller — making subsequent
    /// `publish_json` calls stamp the wrong principal. The outer
    /// invocation's principal owns every outbound publish for the
    /// duration of the interceptor.
    pub interceptor_active: bool,
    /// The unique session UUID for this plugin's execution state.
    pub capsule_uuid: uuid::Uuid,
    /// Workspace root directory (file operations are confined here).
    ///
    /// For a non-git workspace this is the copy-on-write **merged** path (an
    /// APFS clone / overlayfs mount), NOT the pristine workspace — so the fs
    /// host AND spawned processes (whose sandbox writable root + cwd are this
    /// path) share one filesystem, and a spawned `cargo` sees the CoW writes.
    /// See `astrid_vfs::workspace_cow`.
    pub workspace_root: PathBuf,
    /// Pristine hosted portal path for durable command grants.
    /// Distinct from [`Self::workspace_root`] (runtime-effective merged/git
    /// path used for FS confinement). `HostedPortal`: the source before `CoW`.
    /// Git-managed: same as `workspace_root`. Astrid filesystem: empty.
    pub hosted_workspace_root: PathBuf,
    /// Copy-on-write bookkeeping dirs (the overlayfs upper/work, or the pristine
    /// workspace under APFS) that the OS sandbox MUST mask from spawned
    /// children, so a child cannot write them directly and bypass the workspace
    /// promote/rollback gate. Threaded into `SandboxCommand::wrap_with_injections`
    /// as `extra_masks` on every spawn. Empty for git-managed / No-CoW workspaces.
    pub spawn_mask_paths: Vec<PathBuf>,
    /// The Virtual File System (VFS) instance for this plugin.
    pub vfs: Arc<dyn astrid_vfs::Vfs>,
    /// The root capability handle for the VFS.
    pub vfs_root_handle: astrid_capabilities::DirHandle,
    /// Load-time canonical Astrid workspace branch for this runtime owner.
    /// `None` is intentional for neutral SystemResident state.
    pub workspace: Option<PrincipalMount>,
    /// Resolver used to install an authenticated caller's branch on a shared
    /// SystemResident runtime.
    pub workspace_mount_resolver: Option<Arc<dyn WorkspaceMountResolver>>,
    /// Kernel-owned native projection broker for spawned processes over
    /// path-free Astrid storage. Hosted portals leave this unset.
    #[cfg(not(target_family = "wasm"))]
    pub process_storage_mount_broker: Option<Arc<dyn crate::context::ProcessStorageMountBroker>>,
    /// Load-time principal home mount (`home://` paths), bound to the
    /// principal's immutable storage UID. `None` when no durable identity is
    /// admitted.
    pub home: Option<PrincipalMount>,
    /// Live alias-to-UID directory used to bind invocation home views.
    pub principal_directory: astrid_storage::PrincipalDirectory,
    /// Authoritative store used to construct invocation home views.  This is
    /// cloned into each pooled state so recv-path principal switches never
    /// consult native principal-home directories.
    pub principal_store: Option<astrid_storage::RuntimePrincipalStore>,
    /// Load-time principal tmp mount (`/tmp/` paths), backed by private
    /// runtime scratch keyed by immutable principal UID. `None` if unavailable.
    pub tmp: Option<PrincipalMount>,
    /// Load-time authority-scoped KV. Principal runtimes receive their owner's
    /// namespace; SystemResident runtimes receive an explicit system namespace.
    /// Neutral test/lifecycle contexts may use [`HostState::neutral_kv`].
    pub kv: ScopedKvStore,
    /// The real, shared KV backend used to CONSTRUCT per-invocation overlays.
    ///
    /// Used to construct authenticated per-message overlays without deriving
    /// them from another scoped view.
    pub kv_backend: Arc<dyn astrid_storage::KvStore>,
    /// Per-invocation KV store scoped to the calling principal.
    ///
    /// Set by `WasmEngine::invoke_interceptor` (and the `ipc::recv` path) for
    /// EVERY invocation that carries a principal — the owner/`default` included.
    /// Host functions use [`effective_kv`](Self::effective_kv) which returns this
    /// overlay when set and the runtime-owned [`kv`](Self::kv) otherwise.
    pub invocation_kv: Option<ScopedKvStore>,
    /// Per-invocation home mount for the calling principal.
    ///
    /// Populated by `WasmEngine::invoke_interceptor` when the IPC message's
    /// principal differs from `self.principal`. When set, overrides `home`
    /// for scheme resolution and security gate checks. Cleared on exit.
    pub invocation_home: Option<PrincipalMount>,
    /// Per-invocation authoritative workspace branch for the authenticated
    /// caller. Cleared when the invocation returns to the pool.
    pub invocation_workspace: Option<PrincipalMount>,
    /// Per-invocation tmp mount for the calling principal. Same lifecycle
    /// as `invocation_home`.
    pub invocation_tmp: Option<PrincipalMount>,
    /// Per-invocation secret store scoped to the calling principal.
    ///
    /// Set by `WasmEngine::invoke_interceptor` when the IPC message's
    /// principal differs from `self.principal`. When set, overrides
    /// `secret_store` so `has_secret` and future secret host fns scope
    /// reads/writes to the invoking principal. Cleared on exit.
    pub invocation_secret_store: Option<Arc<dyn SecretStore>>,
    /// Per-invocation capsule log file scoped to the calling principal.
    ///
    /// Same lifecycle as [`invocation_secret_store`](Self::invocation_secret_store).
    /// When set, `astrid_log` writes to the invoking principal's UID-scoped
    /// native operational log instead of the capsule owner's.
    pub invocation_capsule_log: Option<Arc<std::sync::Mutex<std::fs::File>>>,
    /// Per-invocation quota profile for the invoking principal.
    ///
    /// Set by [`WasmEngine::invoke_interceptor`](super::WasmEngine::invoke_interceptor)
    /// after resolving the invoking principal's `PrincipalProfile` through
    /// the shared [`PrincipalProfileCache`](crate::profile_cache::PrincipalProfileCache).
    /// Host functions that gate on per-principal sub-budgets (IPC
    /// throughput, background processes, HTTP streams) read this through
    /// [`effective_profile`](Self::effective_profile). Cleared on exit.
    ///
    /// Resolved on BOTH per-invocation paths: the dispatcher-driven
    /// interceptor path (`invoke_interceptor`) and the guest-pulled
    /// `ipc::recv` path ([`install_recv_invocation_context`](Self::install_recv_invocation_context),
    /// via [`profile_cache`](Self::profile_cache)). With no cache (tests /
    /// single-tenant), this stays `None` and
    /// [`effective_profile`](Self::effective_profile) substitutes the
    /// process-global default. With a cache, only the bootstrap `default`
    /// principal retains the missing-file compatibility fallback; a missing
    /// profile for any non-default principal is an authorization failure.
    pub invocation_profile: Option<Arc<astrid_core::profile::PrincipalProfile>>,
    /// Whether the current invocation's profile resolved successfully.
    ///
    /// A restricted synthetic profile supplies fail-closed quota/network/process
    /// values after a recv-path resolution error, while this bit prevents the
    /// guest from publishing IPC effects until real policy is available again.
    pub invocation_profile_authorized: bool,
    /// Shared per-principal lifecycle admission fence. Run-loop host calls
    /// acquire a guard from this tracker and retain it through the actual
    /// effect, so deletion waits for effects admitted before retirement.
    pub(super) principal_invocations: Option<Arc<super::PrincipalInvocationTracker>>,
    /// Shared profile-cache handle, used by the `ipc::recv` path to resolve
    /// the invoking principal's [`PrincipalProfile`](astrid_core::profile::PrincipalProfile)
    /// into [`invocation_profile`](Self::invocation_profile).
    ///
    /// The interceptor path resolves the profile in
    /// [`WasmEngine::invoke_interceptor`](super::WasmEngine::invoke_interceptor)
    /// and installs it directly; the guest-pulled `ipc::recv` path has no
    /// dispatcher frame to do that, so
    /// [`install_recv_invocation_context`](Self::install_recv_invocation_context)
    /// resolves through this handle. `None` in tests / single-tenant — the
    /// per-principal quota fields then fall back to the default profile.
    pub profile_cache: Option<Arc<crate::profile_cache::PrincipalProfileCache>>,
    /// Per-invocation env overlay for the invoking principal, loaded from the
    /// host-only typed KV projection when a dispatcher or recv path establishes
    /// a per-invocation context. `get_config` checks this overlay before the
    /// manifest defaults in [`config`](Self::config).
    pub invocation_env_overlay: Option<HashMap<String, String>>,
    /// System Event Bus for IPC publish/subscribe.
    pub event_bus: astrid_events::EventBus,
    /// Private secret replies; unset until an authenticated responder is bound.
    pub secret_elicits: Option<Arc<crate::elicitation::PendingSecretElicits>>,
    /// Shared generation-publication fence for every routed subscription this
    /// Store creates. Prepared runtimes keep it staged until registry publish.
    pub route_admission_gate: astrid_events::RouteAdmissionGate,
    /// Rate limiter for IPC message publishing.
    ///
    /// `Arc` so a capsule's pool of `Store`s shares one limiter — otherwise
    /// each pooled `Store` would get its own budget and the per-capsule
    /// throughput cap would be `pool_size`× too loose (issue #816). The
    /// limiter is internally concurrent (`DashMap`), so shared `&self` access
    /// is contention-free.
    pub ipc_limiter: Arc<astrid_events::ipc::IpcRateLimiter>,
    /// Plugin configuration from the manifest.
    ///
    /// Holds only **non-secret** env values (the `[env]` declarations
    /// in `Capsule.toml` whose `type` is not `"secret"` — base URLs,
    /// model names, log levels, etc.). Secret-typed keys are
    /// resolved live in [`crate::engine::wasm::host::sys`] through
    /// `resolve_secret` and the host-only typed SecretStore projection instead
    /// of being preloaded here.
    pub config: HashMap<String, serde_json::Value>,
    /// Manifest-declared secret-typed env keys. Populated at load
    /// time from `manifest.env` entries with `type = "secret"`. Used
    /// by [`crate::engine::wasm::host::sys::Host::get_config`] to
    /// route reads through the file-per-secret store instead of
    /// `config`. The scope (per-agent vs host-wide) is an
    /// operator-side decision at `astrid secret set` time, not a
    /// manifest declaration, so the kernel always tries per-agent
    /// first and falls through to host-wide regardless of where the
    /// operator stored the value.
    pub secret_env: std::collections::HashSet<String>,
    /// Secret values `get_config` handed to this instance, kept host-side so
    /// the HTTP audit redacts them from request commitments.
    pub revealed_secrets: crate::engine::wasm::host::http::RevealedSecrets,
    /// Tool result published during the current invocation, for its audit.
    pub tool_result: Option<crate::engine::wasm::host::tool_audit::ToolResultCapture>,
    /// Legacy secret-root context retained for migration compatibility.
    /// Runtime secret lookup never reads this path; released homes must be
    /// imported explicitly with [`astrid_storage::env::import_legacy_scope`].
    pub file_secret_root: Option<std::path::PathBuf>,
    /// IPC topic patterns this capsule is allowed to publish to.
    /// Empty means DENY ALL (fail-closed).
    pub ipc_publish_patterns: Vec<String>,
    /// IPC topic patterns this capsule is allowed to subscribe to.
    /// Empty means DENY ALL (fail-closed).
    pub ipc_subscribe_patterns: Vec<String>,
    /// Optional security gate for gated operations (HTTP, file I/O).
    pub security: Option<Arc<dyn CapsuleSecurityGate>>,
    /// Hook manager for executing user scripts synchronously via airlock.
    pub hook_manager: Option<Arc<dyn std::any::Any + Send + Sync>>,
    /// Shared capsule registry for `hooks::trigger` fan-out dispatch.
    ///
    /// When set, the `astrid_trigger_hook` host function can iterate the
    /// registry to find capsules with matching interceptors, invoke them,
    /// and collect responses. This is the kernel mechanism that WASM
    /// capsules use to dispatch hooks to other capsules.
    pub capsule_registry: Option<Arc<tokio::sync::RwLock<crate::registry::CapsuleRegistry>>>,
    /// Tokio runtime handle for bridging async operations in sync host functions.
    pub runtime_handle: tokio::runtime::Handle,
    /// Whether the plugin manifest declares `CapsuleCapability::Uplink`.
    ///
    /// Used to gate `astrid_register_uplink` — only uplink plugins
    /// are allowed to register uplinks.
    pub has_uplink_capability: bool,
    /// The calling capsule's OWN held capability NAMES, precomputed at load
    /// from `manifest.capabilities` via
    /// [`CapabilitiesDef::held_names`](crate::manifest::CapabilitiesDef::held_names).
    ///
    /// Backs `astrid:sys/host.enumerate-capabilities`, which is **infallible**
    /// — so it reads this owned, lock-free snapshot rather than the
    /// `capsule_registry` (whose lookup can fail with `registry-unavailable`,
    /// the failure mode `check-capsule-capability` carries but `enumerate`
    /// must not). Capsule capabilities are fixed at load (the grant/revoke
    /// model is principal-scoped, a separate axis), so a snapshot taken once
    /// is correct for the capsule's whole lifetime and across the pool.
    pub capability_names: Vec<String>,
    /// Operator-approved local-egress allowlist for THIS capsule, as
    /// `host:port` / `host:*` patterns (from `[security.capsule_local_egress]`,
    /// keyed by capsule id). Endpoints listed here are exempt from the
    /// `astrid:http` SSRF airlock for this capsule only — the sanctioned way
    /// to reach a loopback/private LLM endpoint. Like
    /// [`capability_names`](Self::capability_names) this is fixed at load and
    /// snapshotted onto every pooled instance (operator config does not change
    /// per principal or per invocation); the pool reset must NOT clear it.
    /// Empty = no exemptions (fail-closed).
    pub local_egress: Vec<String>,
    /// Resolved operator ceilings for the `astrid:http` host (timeouts,
    /// redirect/stream caps, buffered-body limit), from the `[http]` config
    /// section. A GLOBAL value — the same for every capsule (unlike the
    /// per-capsule [`local_egress`](Self::local_egress)); resolved once by the
    /// daemon and snapshotted onto every pooled instance at load. The request
    /// path reads its defaults and ceilings off this instead of module
    /// constants. [`HttpLimits::default`](super::limits::HttpLimits::default)
    /// reproduces the host's historical hardcoded constants.
    pub http_limits: super::limits::HttpLimits,
    /// Whether this capsule's OWNER principal holds `audit:read_all`,
    /// resolved at LOAD the PRIVILEGED way (against the profile cache +
    /// live group config — **not** the manifest, unlike
    /// [`has_uplink_capability`](Self::has_uplink_capability) which is read
    /// straight off `manifest.capabilities.uplink`).
    ///
    /// Governs the audit-topic subscription seam: `true` ⇒ a subscription
    /// covering `astrid.v1.audit.entry` is the unscoped firehose (every
    /// principal's entries, as before); `false` (the default) ⇒ the
    /// subscription is route-scoped to the owner principal so it observes
    /// only its own audit entries. Fail-secure: `false`. A capsule cannot
    /// flip this via its `Capsule.toml` — it chooses neither its load
    /// principal nor that principal's operator-owned capabilities.
    pub audit_firehose: bool,
    /// Sender for inbound messages from uplink plugins.
    ///
    /// Set during plugin loading when the manifest declares
    /// [`CapsuleCapability::Uplink`](crate::CapsuleCapability). Feeds into
    /// the gateway's inbound router.
    pub inbound_tx: Option<mpsc::Sender<InboundMessage>>,
    /// Uplinks registered by the WASM guest via `astrid_register_uplink`.
    pub registered_uplinks: Vec<UplinkDescriptor>,
    /// Optional natively bound unix listener.
    pub cli_socket_listener: Option<Arc<tokio::sync::Mutex<LocalListener>>>,
    /// Active lifecycle phase, if any. `None` during normal runtime.
    /// Set to `Some(Install)` or `Some(Upgrade)` during lifecycle dispatch.
    /// Gates the `astrid_elicit` host function.
    pub lifecycle_phase: Option<LifecyclePhase>,
    /// Runtime-owned secret store. Principal runtimes use the owner namespace;
    /// SystemResident runtimes use an explicit system namespace. Neutral test
    /// contexts use a deny-all store.
    pub secret_store: Arc<dyn SecretStore>,
    /// Readiness signal sender for run-loop capsules.
    ///
    /// When the WASM guest calls `astrid_signal_ready`, the host sends `true`
    /// on this channel. The kernel waits on the corresponding receiver before
    /// loading dependent capsules.
    pub ready_tx: Option<watch::Sender<bool>>,
    /// Bounded-concurrency semaphore for **blocking** host calls — the ones
    /// that `block_in_place` + `block_on` and pin a tokio worker for the whole
    /// permit-held wait (KV, identity, sys, fs, the net/process security gates,
    /// DNS, sockets). Sized to roughly `cores - 2` so blocking host work cannot
    /// starve the tokio scheduler. Created via
    /// [`default_blocking_semaphore`](HostState::default_blocking_semaphore);
    /// override via `[capsule].host_blocking_concurrency`.
    pub blocking_semaphore: Arc<Semaphore>,
    /// Bounded-concurrency semaphore for **async-I/O** host calls — the ones
    /// that `.await` real I/O directly and free the tokio worker while pending
    /// (HTTP request/stream, `ipc::recv`). Sized much larger than
    /// [`blocking_semaphore`](Self::blocking_semaphore) and clamped by the
    /// process file-descriptor limit, since each in-flight call may hold a
    /// socket — this is the outbound-throughput gate the LLM path rides on
    /// (`astrid#816`). Created via
    /// [`default_io_semaphore`](HostState::default_io_semaphore); override via
    /// `[capsule].host_io_concurrency`.
    pub io_semaphore: Arc<Semaphore>,
    /// Cooperative cancellation token for long-running host function calls.
    ///
    /// Triggered during capsule unload to unblock every blocking host
    /// fn that races it: `Subscription.recv`, `elicit`, the various
    /// listener `accept` paths, `connect-tcp`, `read`/`read-bytes`/
    /// `write-bytes` on `tcp-stream`, `read-chunk` on `http-stream`,
    /// `pollable.block`, `poll.poll`, `sleep-ns`, and the `wait` /
    /// `spawn` paths on `process`. Streams (`astrid:io/streams`)
    /// short-circuit with `Closed` when this fires; pollables
    /// short-circuit with `Cancelled`.
    pub cancel_token: CancellationToken,
    /// Shared per-principal cancellation-token map (see
    /// [`PrincipalCancelTokens`]). Cloned into every pooled `HostState` like
    /// [`process_tracker`](Self::process_tracker), so cancelling one
    /// principal's token reaches its waits on any pooled instance. Entries are
    /// minted lazily (as children of [`cancel_token`](Self::cancel_token)) by
    /// [`install_invocation_cancel_token`](Self::install_invocation_cancel_token).
    pub principal_cancel_tokens: PrincipalCancelTokens,
    /// Per-invocation cancellation token scoped to the invoking principal.
    ///
    /// Installed alongside the other `invocation_*` overlays for every caller
    /// that carries a present, parseable principal; `None` for principal-less
    /// contexts. Blocking host calls wait on
    /// [`effective_cancel_token`](Self::effective_cancel_token) — this overlay
    /// when set, else the instance [`cancel_token`](Self::cancel_token) — so
    /// retiring one admitted identity can interrupt its in-flight waits without
    /// affecting other identities admitted by a SystemResident service.
    pub invocation_cancel_token: Option<CancellationToken>,
    /// Session token for authenticating CLI socket connections. Only set for
    /// the CLI proxy capsule (which has `net_bind` capability).
    pub session_token: Option<std::sync::Arc<astrid_core::session_token::SessionToken>>,
    /// Interceptor binding metadata, populated during `WasmEngine::load()`
    /// from `[[interceptor]]` entries in `Capsule.toml`. The kernel
    /// matches incoming IPC messages against these patterns and calls
    /// `astrid-hook-trigger` directly — these handles are not
    /// `Resource<Subscription>` references and the guest cannot
    /// consume from them. See [`InterceptorHandle`] for the metadata
    /// shape and `astrid:ipc/host.get-interceptor-bindings` for the
    /// guest-facing accessor.
    pub interceptor_handles: Vec<InterceptorHandle>,
    /// Shared allowance store for capsule-level approval requests.
    ///
    /// When set, the `astrid_request_approval` host function can check
    /// existing allowances before prompting the user. Approvals with
    /// session/always scope create new allowances here.
    pub allowance_store: Option<std::sync::Arc<astrid_approval::AllowanceStore>>,
    /// Shared identity store for resolving platform users to `AstridUserId`.
    ///
    /// When `None`, identity host functions return an error.
    pub identity_store: Option<std::sync::Arc<dyn astrid_storage::IdentityStore>>,
    /// Active HTTP streaming responses, keyed by handle ID.
    ///
    /// Each entry holds a `reqwest::Response` whose body is being consumed
    /// incrementally by `astrid_http_stream_read` plus the principal that
    /// started the stream, so per-principal HTTP-stream caps can be
    /// enforced by creator without blocking other principals on the same
    /// capsule. Cleaned up by `astrid_http_stream_close` or when the
    /// capsule unloads.
    pub active_http_streams: HashMap<u64, crate::engine::wasm::host::http::ActiveHttpStream>,
    /// Monotonic counter for HTTP stream handle IDs.
    /// Starts at 1 (0 reserved as sentinel).
    pub next_http_stream_id: u64,
    /// Tracks active child process PIDs for cancellation.
    ///
    /// Shared with the cancel listener background task. The spawn host function
    /// registers/unregisters PIDs; the listener calls `cancel_all()` when a
    /// `tool.v1.request.cancel` event arrives.
    pub process_tracker: Arc<ProcessTracker>,
    /// Host-owned registry for the PERSISTENT tier of `astrid:process`.
    ///
    /// Cloned (`Arc`) into every pooled `HostState` of a capsule exactly like
    /// `process_tracker`, so a `process-id` minted on one instance is
    /// reattachable from another after a pool reset. Persistent children live
    /// here — off the wasmtime resource table — which is what lets them
    /// survive instance churn.
    pub persistent_processes: Arc<crate::engine::wasm::host::process::PersistentProcessRegistry>,
    /// Live count of accepted/connected streams owned by this Store.
    ///
    /// Retained as a public compatibility mirror for callers that inspect the
    /// per-Store resource count. Capsule-wide quota enforcement uses the
    /// internal atomic below because readiness pollables can reserve a stream
    /// while the guest is outside a host call.
    pub net_stream_count: usize,
    /// Live accepted/connected streams across every pooled Store for this
    /// capsule, including readiness reservations not yet claimed by the guest.
    pub(crate) capsule_net_stream_count: Arc<std::sync::atomic::AtomicUsize>,
    /// Streams reserved by this pooled Store. Reset subtracts this exact
    /// contribution from the shared capsule-wide counter.
    pub(crate) local_net_stream_count: Arc<std::sync::atomic::AtomicUsize>,
    /// Live count of bound inbound TCP listeners, shared by every pooled
    /// store for this capsule. The WIT contract limits the capsule as a whole
    /// to four listeners; a store-local counter would multiply that limit by
    /// the dynamic pool size.
    pub(crate) tcp_listener_count: Arc<std::sync::atomic::AtomicUsize>,
    /// Live count of `SubscriptionEntry` entries. Same rationale as
    /// `net_stream_count`.
    pub subscription_count: usize,
    /// Live count of `ManagedProcess` entries — overall.
    pub process_count_total: usize,
    /// Per-creator-principal count of `ManagedProcess` entries. The
    /// process-spawn gate needs to enforce per-principal sub-budgets
    /// without iterating the whole resource table.
    pub process_count_by_principal:
        std::collections::HashMap<astrid_core::principal::PrincipalId, usize>,
    /// Verified principal bound to each accepted host-local connection,
    /// keyed by the stream resource rep (`u32`). Populated by the
    /// `net.unix-listener.accept` path after a successful per-connection
    /// principal challenge-response (issue #45/#852) and torn down when the
    /// stream resource drops.
    ///
    /// `Arc<DashMap>` so the binding is SHARED across a capsule's pooled
    /// interceptor `HostState` instances exactly like [`process_tracker`](Self::process_tracker):
    /// the same socket-owning capsule may serve a connection from a
    /// different pooled instance than the one that accepted it. Run-loop
    /// workers do not share this map: each worker owns a ResourceTable, so
    /// Wasmtime `u32` reps collide across workers. Each entry
    /// carries the verified principal AND the `key_id` of the device that
    /// authenticated it ([`ConnectionIdentity`]) so the cap-gate can apply the
    /// device's scope as an attenuation floor on the principal's authority.
    pub connection_principals: Arc<dashmap::DashMap<u32, ConnectionIdentity>>,
    /// The verified principal of the source connection whose inbound frame is
    /// currently in flight — the ENFORCEMENT side of
    /// [`connection_principals`](Self::connection_principals) (issue #45/#852).
    ///
    /// Set by the framed [`net::tcp-stream.read`](super::host::net) host fn when
    /// a read returns a data frame on a connection that carries a kernel-bound
    /// principal; cleared to `None` on a closed/pending read. When the uplink
    /// (capsule-cli) forwards that frame via `publish-as`, the host stamps THIS
    /// principal in place of the capsule-supplied name, so a socket client can
    /// no longer name a principal it has not proven (the self-stamp fix). It
    /// holds from one framed read until the next, so a forwarded message AND its
    /// one-shot `client.v1.connect` both attribute to the same verified
    /// principal.
    ///
    /// `None` for an unbound connection (a legacy peer-cred-trusted local
    /// operator), in which case `publish-as` falls back to the supplied name.
    /// Per-instance state, NOT the shared `Arc`: the single pooled run-loop
    /// instance of the uplink both reads the frame and forwards it, so the
    /// binding lives exactly as long as the in-flight frame.
    pub ingress_principal: Option<astrid_core::principal::PrincipalId>,
    /// The device `key_id` of the source connection whose inbound frame is
    /// currently in flight — the per-device companion to
    /// [`ingress_principal`](Self::ingress_principal).
    ///
    /// Set and cleared in LOCKSTEP with `ingress_principal` by the framed
    /// `tcp-stream.read` host fn (same data-frame populate / non-data clear),
    /// from the same [`ConnectionIdentity`] entry, so the principal and the
    /// device that authenticated it never desync onto a later forward. When
    /// the uplink forwards a frame via `publish-as`, the host stamps THIS
    /// `key_id` onto the outbound message's `device_key_id` so the kernel
    /// cap-gate can resolve the device's scope and attenuate the principal's
    /// effective capabilities. `None` for an unbound connection or a binding
    /// that carried no specific device.
    pub ingress_device_key_id: Option<String>,
    /// Host-minted request owner for the source connection whose inbound frame
    /// is currently in flight. Set and cleared with the other ingress identity
    /// fields; `publish-as` propagates it without accepting a guest override.
    pub ingress_request_owner: Option<astrid_events::ipc::RequestOwnerId>,
    /// The transport origin of the source connection whose inbound frame is
    /// currently in flight — the per-frame companion to
    /// [`ingress_principal`](Self::ingress_principal), feeding the host-stamped
    /// [`MessageOrigin`](astrid_events::ipc::MessageOrigin) on a `publish-as`
    /// forward.
    ///
    /// Set to `Some(MessageOrigin::LocalSocket)` by the framed `tcp-stream.read`
    /// host fn ONLY for a kernel-BOUND connection (one with a verified
    /// [`ConnectionIdentity`]), and cleared to `None` on a non-data read or a
    /// read off an unbound connection — in LOCKSTEP with `ingress_principal` /
    /// `ingress_device_key_id` so origin never desyncs from the identity it
    /// describes. When the uplink forwards the frame via `publish-as`, the host
    /// stamps THIS origin onto the outbound message so a downstream egress site
    /// can positively identify a local-operator request. `None` for an unbound
    /// (peer-cred-trusted but unauthenticated) local connection, which earns
    /// `System` (the fail-closed, non-local floor) — an unproven local
    /// connection does NOT earn `LocalSocket`, parallel to how an unbound
    /// principal stamps the reserved `anonymous` identity.
    pub ingress_origin: Option<astrid_events::ipc::MessageOrigin>,
    /// Host-verified principal each INBOUND uplink connection was accepted
    /// under, keyed by stream resource rep (`u32`). The lifecycle registry the
    /// kernel connection counter rides on: `net.unix-listener.{accept,
    /// poll-accept}` inserts on accept and emits `client.v1.connect`; the
    /// stream-resource drop removes and emits `client.v1.disconnect`. Both
    /// emissions stamp the principal stored here, so the pair always balances
    /// on the identical identity (the connection-tracker leak fix).
    ///
    /// Populated for EVERY inbound connection — the handshake-verified
    /// principal, or the reserved `anonymous` for a legacy/unauthenticated peer
    /// — so connect/disconnect balance even when unauthenticated. OUTBOUND TCP
    /// (`connect-tcp`) is never inserted, so a capsule-dialed socket never
    /// moves the client counter. The emitted principal is ALWAYS the
    /// host-verified one (never a guest-supplied name), preserving the
    /// anti-forge boundary (issues #45/#852).
    ///
    /// Distinct from [`connection_principals`](Self::connection_principals),
    /// which stores only authenticated principals (absence ⇒ `publish-as`
    /// anonymous fallback). `Arc<DashMap>` so the binding survives drop landing
    /// on a different pooled instance than the one that accepted.
    pub client_connections: Arc<dashmap::DashMap<u32, astrid_core::principal::PrincipalId>>,
    /// Bound loopback TCP listeners shared across a run-loop capsule's worker
    /// Stores, keyed by `(host, port)`. When `bind_workers > 1`, each of the N
    /// worker Stores runs `run()` and calls `bind_tcp` for the same address;
    /// the first worker binds the socket and the rest dedupe onto its
    /// listener here, so all N block on `accept()` against ONE OS accept
    /// queue. Holder count lives on the entry: last slot drop evicts it so
    /// the OS socket closes. Cloned into worker Stores only when
    /// `bind_workers > 1`; interceptor / non-worker pool instances each get
    /// a fresh map so a concrete-port bind is not accidentally shared.
    pub shared_listeners: Arc<dashmap::DashMap<(String, u16), SharedTcpListener>>,
    /// Whether `bind_tcp` may clone a concrete-port socket from
    /// [`shared_listeners`](Self::shared_listeners). True only for
    /// `bind_workers > 1` worker Stores. N=1 (and interceptor/lifecycle
    /// HostStates) keep the historical AddressInUse on a second bind.
    pub share_tcp_listeners: bool,
    /// Bound run-loop CPU-bound signal: set `true` by the ipc `recv` host fn
    /// each time the guest blocks on recv, read + cleared by the run-loop's
    /// epoch-deadline callback once per window.
    ///
    /// This is the cooperative-yield signal that distinguishes a legitimate
    /// recv/accept loop (sets it every iteration → never trapped) from a
    /// no-recv spinner (never sets it → interrupt-trapped after
    /// `MAX_NO_YIELD_WINDOWS`). Only the dedicated, mutex-guarded run-loop
    /// Store reads it; pooled/lifecycle Stores leave it inert. Single Store =
    /// single thread, so the callback and the host fn never race.
    pub recv_yielded: bool,
    /// Bound run-loop CPU-bound counter: consecutive epoch windows in which
    /// the guest burned CPU without a single `recv` (`recv_yielded` stayed
    /// false). The run-loop epoch callback increments it each no-recv window
    /// and traps the guest once it reaches `MAX_NO_YIELD_WINDOWS`; a recv
    /// resets it to 0. Inert for pooled/lifecycle Stores.
    pub no_yield_windows: u32,
    /// Synchronous sink for sensitive per-action host calls (fs read/write/
    /// delete, net connect/bind, process spawn). When `Some`, the fs/net/
    /// process host fns report every allowed, failed, OR denied call to it,
    /// stamped with [`effective_principal`](Self::effective_principal); the
    /// kernel implementation appends a signed, hash-chained audit entry
    /// synchronously. `None` in tests / any context with no audit log
    /// (the report is then a no-op — observability `tracing` lines still
    /// fire). Snapshotted onto every pooled instance at load like the other
    /// shared kernel handles; never cleared by the pool reset.
    pub audit_sink: Option<std::sync::Arc<dyn crate::audit_sink::HostAuditSink>>,
}

impl wasmtime_wasi::WasiView for HostState {
    fn ctx(&mut self) -> wasmtime_wasi::WasiCtxView<'_> {
        wasmtime_wasi::WasiCtxView {
            ctx: &mut self.wasi_ctx,
            table: &mut self.resource_table,
        }
    }
}

impl HostState {
    /// Namespace of the neutral, fail-closed KV fallback.
    ///
    /// A real per-principal namespace is `{principal}:capsule:{capsule_id}` and a
    /// [`PrincipalId`](astrid_core::PrincipalId) is restricted to `[a-zA-Z0-9_-]`.
    /// The `.` in `neutral.fail-closed` therefore cannot appear in any real
    /// principal segment, so this namespace can never collide with a principal's
    /// namespace even by construction. Belt-and-braces: the neutral store is also
    /// backed by a *separate* in-memory store (see [`Self::neutral_kv`]), so it is
    /// physically isolated from the persistent backend regardless of namespace.
    pub const NEUTRAL_KV_NAMESPACE: &'static str = "neutral.fail-closed:capsule";

    /// Build the NEUTRAL, physically-isolated KV fallback store.
    ///
    /// Backed by a fresh [`MemoryKvStore`](astrid_storage::MemoryKvStore) — NOT
    /// the shared persistent backend — so a stray read is empty and a stray write
    /// cannot reach any principal's persistent namespace. This is the store a
    /// neutral test/lifecycle context can use without touching persistent state.
    #[must_use]
    pub fn neutral_kv() -> ScopedKvStore {
        ScopedKvStore::new(
            Arc::new(astrid_storage::MemoryKvStore::new()),
            Self::NEUTRAL_KV_NAMESPACE,
        )
        .expect("neutral KV namespace is a valid, non-empty, null-free constant")
    }

    /// Build the NEUTRAL, deny-all secret-store fallback.
    ///
    /// See [`astrid_storage::DenySecretStore`]. Used by neutral test/lifecycle
    /// contexts that have no persistent authority namespace.
    #[must_use]
    pub fn neutral_secret_store() -> Arc<dyn SecretStore> {
        Arc::new(astrid_storage::DenySecretStore::new())
    }

    /// Register a uplink descriptor (called from the host function).
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The per-capsule uplink limit ([`MAX_UPLINKS_PER_CAPSULE`]) has been reached.
    /// - A uplink with the same name and platform already exists.
    pub fn register_uplink(&mut self, descriptor: UplinkDescriptor) -> Result<(), &'static str> {
        if self.registered_uplinks.len() >= MAX_UPLINKS_PER_CAPSULE {
            return Err("uplink registration limit reached");
        }
        // Reject duplicate name+platform combinations
        let duplicate = self
            .registered_uplinks
            .iter()
            .any(|c| c.name == descriptor.name && c.platform == descriptor.platform);
        if duplicate {
            return Err("duplicate uplink name and platform");
        }
        self.registered_uplinks.push(descriptor);
        Ok(())
    }

    /// Return the registered uplinks.
    #[must_use]
    pub fn uplinks(&self) -> &[UplinkDescriptor] {
        &self.registered_uplinks
    }

    /// Default **blocking** host-call semaphore (host-derived).
    ///
    /// Sized to roughly `cores - 2`, reserving headroom for the tokio scheduler
    /// and event dispatch so blocking host work cannot starve them. See
    /// [`limits::host_blocking_concurrency_default`](super::limits::host_blocking_concurrency_default).
    /// Used by the lifecycle-hook and test paths; the pooled interceptor path
    /// sizes from the resolved [`CapsuleRuntimeLimits`](super::limits::CapsuleRuntimeLimits).
    #[must_use]
    pub fn default_blocking_semaphore() -> Arc<Semaphore> {
        Arc::new(Semaphore::new(
            super::limits::host_blocking_concurrency_default(),
        ))
    }

    /// Default **async-I/O** host-call semaphore (host-derived, fd-clamped).
    ///
    /// Sized much larger than the blocking semaphore and clamped by the process
    /// file-descriptor limit. See
    /// [`limits::host_io_concurrency_default`](super::limits::host_io_concurrency_default).
    #[must_use]
    pub fn default_io_semaphore() -> Arc<Semaphore> {
        Arc::new(Semaphore::new(super::limits::host_io_concurrency_default()))
    }

    /// Set the inbound message sender.
    pub fn set_inbound_tx(&mut self, tx: mpsc::Sender<InboundMessage>) {
        self.inbound_tx = Some(tx);
    }

    /// Debug-only consistency check for authenticated per-message overlays.
    /// A present caller must have an explicit KV/secret scope rather than
    /// accidentally falling through to a different runtime authority.
    ///
    /// Deliberately scoped to a *present, parseable* caller principal (owner
    /// included — no longer excused when the caller equals the owner, since the
    /// fallback is neutral, not the owner's data). A caller whose principal is
    /// **absent/unparseable** is intentionally NOT asserted: principal-less
    /// system and lifecycle events (e.g. capsule-react's
    /// `astrid.v1.watchdog.tick`, capsule-registry's `astrid.v1.capsules_loaded`)
    /// are legitimately dispatched with no caller principal and fall back to the
    /// neutral placeholder — never a specific principal's private state — so a
    /// blanket assert on the absent case would fire on sound paths. Relates to
    /// #977, #1069.
    ///
    /// Not applied to `invocation_home` / `invocation_tmp` / `invocation_capsule_log`:
    /// those legitimately stay `None` for unregistered principals and on the sync
    /// recv path (the VFS bundle registration gate and log-open registration
    /// gate); the neutral fallback denies rather than exposing another principal.
    #[cfg(debug_assertions)]
    fn debug_assert_invocation_field_set(&self, is_set: bool, field_name: &str) {
        let caller_has_principal = self
            .caller_context
            .as_ref()
            .and_then(|m| m.principal.as_deref())
            .and_then(|p| astrid_core::PrincipalId::new(p).ok())
            .is_some();
        if caller_has_principal && !is_set {
            debug_assert!(
                false,
                "a caller principal is in scope but {field_name} is None — the effective_* accessor \
                 would fall back to the NEUTRAL placeholder, denying the caller its own scope",
            );
        }
    }
}

#[path = "host_state_connection.rs"]
mod connection;
#[path = "host_state_effective.rs"]
mod effective;
#[path = "host_state_hook.rs"]
mod hook;
#[path = "host_state_invocation.rs"]
mod invocation;

#[cfg(test)]
#[path = "host_state_tests.rs"]
mod tests;

#[cfg(test)]
#[path = "host_state_cancel_tests.rs"]
mod cancel_tests;
